### ISSUE TITLE
Help please.

### ISSUE THREAD

**Issue by CantoroMC** [bmeneg/coc-perl#2]
After installing the extension with CocInstall coc-perl, it does not appear as a source. What can i do to fix this?

**Comment by ghost** [comment]
@CantoroMC 
Hi
Have you already install Perl::LanguageServer via cpan?

**Comment by CantoroMC** [comment]
Yes of course i've followed the instruction on the readme file.
I've encountered the same problem with coc-bibtex (i.e after the installation of the extension, i can configure it and coc-json shows the completion items for the extension but when i open a file the extension is not loaded)
Probably i m missing something.

**Comment by ghost** [comment]
@CantoroMC 
Could you kindly paste your vimrc and coc-settings.json?

Also, please command 'perl -e "use Perl::LanguageServer"' on shell. If there is no warning, it's fine.
And  :CocInfo in vim.

**Comment by CantoroMC** [comment]
@ryuta69 Thanks for your help

1. Neovim Config: https://github.com/CantoroMC/dotfiles/blob/master/nvim/config/init.vim

2. Coc settings https://github.com/CantoroMC/dotfiles/blob/master/nvim/config/coc-settings.json

3 .CocInfo Output:

> ## versions
>
> vim version: NVIM v0.4.4
> node version: v14.12.0
> coc.nvim version: 0.0.79-8a5b4b2f92
> coc.nvim directory: /home/cantoro/.local/share/nvim/plugged/coc.nvim
> term: st-256color
> platform: linux
> 
> ## Output channel: snippets
> 
> [Info 6:21:30 PM] Using ultisnips directories: UltiSnips /home/cantoro/.config/coc/ultisnips
> [Info 6:21:30 PM] Using ultisnips python command: pyx
> 
> ## Output channel: highlight
> 
> [Info  - 6:21:30 PM] Highlight server running in node v14.12.0

4. The use of the language server gives no error.

**Comment by ghost** [comment]
@CantoroMC thank you very much, I will look into!

CocInfo's output was made when you opened perl file, right? Interesting.

**Comment by CantoroMC** [comment]
Yes, otherwise it will have no reason to load the extension.
I've also tried with a minimal vim configuration, with only coc plugin, and the result is the same.

**Comment by ghost** [comment]
@CantoroMC 

Not sure yet, but could you kindly debug below when you have a time?

1. Go to `~/.config/coc/extensions/node_modules/coc-perl`
2. `rm -rf dist node_modules`
3. `yarn install`
4. Please paste the log here

**Comment by CantoroMC** [comment]
@ryuta69 Here's the output of the build, which fails
 
yarn install v1.22.5
warning ../../package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
warning coc-perl@1.0.0: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
warning eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
$ npx npm-run-all clean build
npx: installed 60 in 3.965s
yarn run v1.22.5
warning ../../package.json: No license field
warning coc-perl@1.0.0: The engine "coc" appears to be invalid.
$ rimraf dist
Done in 0.13s.
yarn run v1.22.5
warning ../../package.json: No license field
warning coc-perl@1.0.0: The engine "coc" appears to be invalid.
$ webpack
/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/webpack-cli/bin/cli.js:281
                throw err;
                ^
 
Error: Cannot find the "/home/cantoro/.config/coc/extensions/node_modules/coc-perl/tsconfig.json" file.
Please check webpack and ForkTsCheckerWebpackPlugin configuration.
Possible errors:
  - wrong `context` directory in webpack configuration (if `configFile` is not set or is a relative path in the fork plugin configuration)
  - wrong `typescript.configFile` path in the plugin configuration (should be a relative or absolute path)
    at Object.assertTypeScriptSupport (/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/TypeScriptSupport.js:40:15)
    at ForkTsCheckerWebpackPlugin.apply (/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:42:33)
    at webpack (/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/webpack/lib/webpack.js:51:13)
    at processOptions (/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/webpack-cli/bin/cli.js:272:16)
    at /home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/yargs/yargs.js:576:18)
    at /home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/cantoro/.config/coc/extensions/node_modules/coc-perl/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.

**Comment by ghost** [comment]
@CantoroMC 
Oh, it was my mistake. I'm sorry.

I fixed here,
https://github.com/ryuta69/coc-perl/commit/a41ab34648f0bc6835ba67ba8130ebbb2b0b0b7a

now if you follow below, it must work.

1. `:CocUninstall coc-perl` or remove directly `~/.config/coc/extensions/node_modules/coc-perl`
2. Open vim (As I see your vimrc, it will automatically install newest coc-perl because you use g:coc_global_extensions. Otherwise `:CocInstall coc-perl`).
3. See if it works.

Thank you very much, it's a good catch.
(I found this mistake exists in coc-tsserver as well)

**Comment by CantoroMC** [comment]
@ryuta69 
Is working but it does not provide source completion. Is it right?
Anyway coc-tsserver works fine for me.

**Comment by ghost** [comment]
@CantoroMC 
Yes, there is no perl lsp which can do source complete currently, so this can't either.

coc tsserver maybe only requires dist source that already exists in npm module, and not necessary to run build. If we try to yarn install inside coc/extensions/coc-tsserver, it occurs error.
While coc-perl needs to conplete build.

**Comment by CantoroMC** [comment]
@ryuta69 Thanks for you kindness, and goodbye
