### ISSUE TITLE
Add support for PerlNavigator

### ISSUE THREAD

**Issue by bmeneg** [bmeneg/coc-perl#25]
[PerlNavigator](https://github.com/bscan/PerlNavigator) is gaining a really nice traction from Perl community as a new and promising language server to Perl, which was mentioned by @oalders on his [talk at TPRC 2023](https://www.youtube.com/watch?v=areXIy7UKyA) and I also had the opportunity to have a quick chat with its maintainer (@bscan) on [Reddit](https://www.reddit.com/r/perl/comments/14lxmyc/perllanguageserver_in_visual_studio_should/) about adding its support to coc-perl, thus enabling a quick and easy language server setup with sane defaults for VIM/NeoVIM users.

Right now, coc-perl is fully dedicated to [Perl::LanguageServer](https://github.com/richterger/Perl-LanguageServer), which is in active development too (although PR integration might take some time). The idea **is not** to remove Perl::LanguageServer support from coc-perl, but **add** PerlNavigator as an alternative to the user.

I'm not quite sure, yet, which will be chosen as the "default" language server, but time and experimentation will tell.
The way I envision it is:

- [x]  In coc-settings.json, Perl::LanguageServer will be referenced as `pls` and PerlNavigator as `navigator`;
- [x]  Only one should be enabled at a time;
- [x]  Specific server options will have its own namespace, ie. `perl.nagivator.enable = true` or `perl.pls.enable = true`;
- [x]  Extension specific options will be kept on the root property namespace, ie. `perl.logFile`;
- [ ]  Extension should check which server is installed at user's machine before enabling one or another;
- [x]  In the first versions, in case both server are enabled by the user, extension should present an error message and exit.

More to come...

Q: Will it completely fork from how usually coc.nvim extensions work in other languages, which usually a simple copy'n'paste from VSCode configuration is enough? 
A: Yes, but I'll figure out some way to keep things backwards-compatible, which depends on how PerlNavigator works, which I'm not really aware of yet.

**Comment by bmeneg** [comment]
Ok, the first bits for supporting PerlNavigator are ready to be integrated.

The only different so far is that Perl::LanguageServer in coc-settings.json must be referenced as `p::ls` (or the original `perl` for backwards compatibility) instead of `pls`. I made this change because I wasn't aware of another LSP project for Perl specifically named [PLS](https://github.com/FractalBoy/perl-language-server). Even though PLS seems to be stagnated, to avoid future confusing I decided to change the property namespace to `p::ls`.

The last point I didn't resolve is about checking server's installation on user's machine, that's TBD soon.

**Comment by oalders** [comment]
@bmeneg I'm wondering if it's worthwhile setting up a `perl-ide` GitHub org to track making these kinds of improvements across different repositories and orgs.

**Comment by bmeneg** [comment]
@oalders When you say "track", do you mean moving all known projects related to Perl IDE under that org or do you mean a simpler approach like creating a `awesome-perl-ide` project with a README file linking all the projects?

I think the first is an awesome idea, we just need to make to capture every author in a good mood :-P.
For the second it would be at least helpful.

**Comment by oalders** [comment]
@bmeneg I think maybe a little of both. If someone has a plugin or something they'd like to move under the umbrella of the org, we could do that. 

I was mostly thinking to set up a GitHub project that could track issues like "Add Perl support to this vim plugin", "find someone to fix this thing in vim-perl", fix syntax highlight of X on GitHub etc.

Adding the awesome repo would be good too. I'd probably prefer an opinionated awesome where you'd say "these are the language servers, but probably use this one first", so that new people can be guided in the right direction.

So maybe all of the above?

**Comment by bmeneg** [comment]
@oalders so probably all the above :D
We already have 2 new projects for the org then: "Perl-Support" and "Awesome-Perl" 😆. I would be happy to place coc-perl there as well.

Do you think we can just come up with the org and start asking interesting projects to join (eg. PerlNavigator)?
Btw, for the awesome-perl it seems we already have a candidate: https://github.com/uhub/awesome-perl: the list is quite long, but doesn't seem to be opinionated at all and deserves a re-structuration.

**Comment by oalders** [comment]
> Do you think we can just come up with the org and start asking interesting projects to join (eg. PerlNavigator)?

I've sent you an org invite. How about we get things started there and then let people know they can move projects over once we're properly up and running?

There is also https://github.com/thibaultduponchelle/perlres as a good base list of resources. Feel free to invite others you think may be interested.
